const products = [
  { ProductName: 'Plain', ProductPrice: 2.50 },
  { ProductName: 'Everything', ProductPrice: 3.25 },
  { ProductName: 'Black + White Sesame Seed', ProductPrice: 3.25 },
  { ProductName: 'Za\'atar', ProductPrice: 3.25 },
  { ProductName: 'Aleppo Pepper', ProductPrice: 3.25 },
  { ProductName: 'Dill Pickle Cheddar', ProductPrice: 3.25 },
  { ProductName: 'Sweet + Spicy Parmesan', ProductPrice: 3.25 },
  { ProductName: 'Blueberry', ProductPrice: 3.25 },
  { ProductName: 'Chai', ProductPrice: 3.25 },
  { ProductName: 'French Toast', ProductPrice: 3.25 },
  { ProductName: 'Sesame Seed', ProductPrice: 3.25 },
  { ProductName: 'Spicy Everything', ProductPrice: 3.25 },
  { ProductName: 'Poppy Seed', ProductPrice: 3.25 },
  { ProductName: 'Rosemary + Sea Salt', ProductPrice: 3.25 },
  { ProductName: '2-Cheese', ProductPrice: 3.25 },
  { ProductName: 'Jalapeno + Cheddar', ProductPrice: 3.25 },
  { ProductName: 'Cajun', ProductPrice: 3.25 },
  { ProductName: 'Cinnamon Raisin', ProductPrice: 3.25 },
  { ProductName: 'Chocolate Chip', ProductPrice: 3.25 },
  { ProductName: 'Sundried Tomato + Roasted Garlic Cream Cheese (8 oz)', ProductPrice: 8.75 },
  { ProductName: 'Strawberry Cream Cheese (8 oz)', ProductPrice: 8.75 },
  { ProductName: 'Spinach + Feta Cream Cheese (8 oz)', ProductPrice: 8.75 },
  { ProductName: 'Plain Cream Cheese (8 oz)', ProductPrice: 8.75 },
  { ProductName: 'Jalapeno + Honey Cream Cheese (8 oz)', ProductPrice: 8.75 },
  { ProductName: 'Garlic + Herb Cream Cheese (8 oz)', ProductPrice: 8.75 },
  { ProductName: 'Dill Pickle Cream Cheese (8 oz)', ProductPrice: 8.75 },
  { ProductName: 'Bacon + Scallion Cream Cheese (8 oz)', ProductPrice: 8.75 },
  { ProductName: 'Apple Cinnamon Cream Cheese (8 oz)', ProductPrice: 8.75 },
];
module.exports = products;